config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  get 'welcome/index'
  get 'welcome/about'
  root to: 'welcome#index'
  
  post :incoming, to: 'incoming#create'

  resources :users, only: [:show] 

  resources :bookmarks, only: [:index]

  resources :topics do
    resources :bookmarks, shallow: true, except: [:index]
  end

  resources :bookmarks, except: [:index] do
    resources :likes, only: [:create, :destroy]
  end




  
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user

  validates_presence_of :topic
  validates_presence_of :url

  has_many :likes, dependent: :destroy

  
  scope :visible_to, -> (user) { user ? all : joins(:bookmark).where('bookmarks.public' => true) }
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy

  validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end

  def created_bookmarks
    bookmarks.includes(:topic)
  end

  def liked_bookmarks
    likes.includes(bookmark: :topic).map(&:bookmark)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end


end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  before_filter :load_topics
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  def index
    @bookmarks = @topic.present? ? @topic.bookmarks : Bookmark.all
    authorize @bookmarks
  end

  def show
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
    authorize @bookmark
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.new(bookmark_params)
    @bookmark.user = current_user
    authorize @bookmark

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @topic, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize @bookmark
  end

  def update
    @topic = @bookmark.topic
    authorize @bookmark

    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @topic, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @bookmark
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    def load_topics
      @topic = Topic.find(params[:topic_id]) if params[:topic_id].present?
    end

    def bookmark_params
      params.require(:bookmark).permit(:url, :user_id, :topic_id)
    end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    @user = User.find_by(email: params[:sender])
    @topic = Topic.find_by(title: params[:subject])

    if @user.nil?
      @user = User.new(email: params[:sender], password: "temp0rary_passw0rd")
      @user.skip_confirmation!
      @user.save!
    end

    if @topic.nil?
      @topic = @user.topics.create(title: params[:subject])
    end

    @bookmark = @topic.bookmarks.create(user_id: @user.id, url: params["stripped-text"])

    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark_id: @bookmark.id)
    
    authorize like
    if like.save
    flash[:notice] = "Bookmark was liked."
      redirect_to @bookmark
    else
      flash[:error] = "There was an error liking the bookmark. Please try again."
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.liked(@bookmark)
    
    authorize like
    if like.destroy
      flash[:notice] = "Bookmark was unliked."
      redirect_to topics_path
    else
      flash[:error] = "There was an error unliking the bookmark."
      render :show
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @topic = Topic.new
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks.all
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    if @topic.save
      flash[:notice] = "Topic was successfully saved."
      redirect_to @topic
    else
      flash[:error] = "There was an error saving the topic. Please try again."
      render :new
    end
  end

  def edit
     @topic = Topic.find(params[:id])
  end

   def update
     @topic = Topic.find(params[:id])
     authorize @topic
     if @topic.update_attributes(topic_params)
       flash[:notice] = "Topic was successfully renamed."
       redirect_to @topic
     else
       flash[:error] = "Error saving topic. Please try again."
       render :edit
     end
   end

  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting the topic."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!

  def show
    @created_bookmarks = current_user.bookmarks
    @liked_bookmarks = current_user.liked_bookmarks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for([@topic, @bookmark]) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> 

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <h1>Bookmarks</h1>
    <div class="row">
      <div class="col-md-8">
      
<table class="table table-hover">
  <thead>
    <tr>
      <th>Topic</th>
      <th>URL</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.topic.title %></td>
        <td><%= bookmark.url %></td>
        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tbody>
</table>
<br>
</div>

  </div>
</div>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form' %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>String:</strong>
  <%= @bookmark.url %>
</p>

<%= render partial: 'likes/like', locals: { bookmark: @bookmark } %>

<div class="col-md-4">
    <%= link_to 'Edit', edit_bookmark_path(@bookmark), class: 'btn btn-success' %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <%= favicon_link_tag 'bear.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
      <ul class="nav nav-tabs">
        <li><%= link_to "Bearded Bear Tracks", root_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "Topics", topics_path %></li>
        <li><%= link_to "Bookmarks", bookmarks_path %></li>

          <div class="pull-right user-info">
           <% if current_user %>
               Hello <%= link_to (current_user.name || current_user.email), current_user %>!
               <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
                 <span class="glyphicon glyphicon-user"></span>
               <% end %>
            
               <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
                <span class="glyphicon glyphicon-log-out"></span>
               <% end %>
      
      <% else %>
        <%= link_to "Sign In", new_user_session_path %> or
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>

      </div>

    </ul>
  </div>

       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>




<%= yield %>
</nav>
</body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
  <div>
     <% if like = current_user.liked(@bookmark) %>
      <%= link_to [bookmark, like], class: 'btn btn-danger', method: :delete do %>
        <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
      <% end %>
     <% else %>
      <%= link_to [bookmark, Like.new], class: 'btn btn-primary', method: :bookmark do %>
        <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
      <% end %>
     <% end %>
   </div>
<% end %> 

app/views/topics/_form.html.erb
<%= form_for [topic] do |f| %>
   <% if topic.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(topic.errors.count, "error") %>.</h4>
       <ul>
         <% topic.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
   <%= form_group_tag(topic.errors[:title]) do %>
     <%= f.label :title%>
     <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic name" %>
   <% end %>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
   <div>
   <%= link_to "Cancel", topics_path, class: 'btn btn-primary' %>
   </div>
 <% end %>

app/views/topics/edit.html.erb
 <h1>Edit Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult cats.</li>
       <li>Be specific enough to invite inquiry.</li>
     </ul>
   </div>
   <div class="col-md-8">
     
   <%= render partial: 'form', locals: { topic: @topic } %>

   </div>
 </div>

app/views/topics/index.html.erb
<div class="container-fluid">
  <h1>Topics</h1>
  
  <div class="row">
    <div class="col-md-8">
      <% @topics.each do |topic| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">

              <%= link_to topic.title, topic %>
            </h4>
          </div>
        </div>
      <% end %>


    </div>
    <div class="col-md-4">
      <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
   <div class="col-md-4">
     <p>Guidelines for Topics</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult cats.</li>
       <li>Be specific enough to invite inquiry.</li>
     </ul>
   </div>
   <div class="col-md-8">
     
   <%= render partial: 'form', locals: { topic: @topic, bookmark: @bookmark } %>
  </div>
</div>

app/views/topics/show.html.erb
<h1>Topic: <%= @topic.title %></h1>

<%= link_to "Edit Topic", edit_topic_path(@topic), class: 'btn btn-primary' %>

<%= link_to "New Topic", new_topic_path(@topic), class: 'btn btn-success' %>

<%= link_to "Delete Topic", @topic, method: :delete, data: { confirm: 'Are you sure you want to delete this topic?' }, class: 'btn btn-danger' %> 
<br><br>

<h1>Bookmarks</h1> 

<table class="table table-hover">
  <thead>
    <tr>
      <th>URL</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topic.bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.url %></td>
        <td><%= link_to 'Show', bookmark %></td>
        
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if policy(Bookmark.new).create? %>
<%= link_to 'New Bookmark', new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Popular Users</h1>
    <p class="lead">Most active users</p>
    <%= render partial: 'users/user', collection: @users %>
  </div>
  <div class="col-md-4">
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="span8 text-left">
    <h1>My Bearded Bear Tracks</h1>
      <% @created_bookmarks.each do |bookmark| %>
        <p><%= bookmark.url %></p>
      <% end %>

    <h1>My Liked Bearded Bear Tracks</h1>
      <% @liked_bookmarks.each do |bookmark| %>
        <p><%= bookmark.url %></p>
      <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>About Bearded Bear Tracks</h1>
<p>Created by Jake Wengroff</p>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to Bearded Bear Tracks!</h1>
      <p>A URL bookmarking service coming soon!</p>
  </div>
</div>